package chatcore

import (
	"errors"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/9router/9router/internal/model"
	"gorm.io/driver/sqlite"
	"gorm.io/gorm"
)

// setupTestDB opens an in-memory SQLite database and migrates the
// ApiKey model. It returns the handle and a teardown helper that the
// caller can ignore (the DB lives only for the test process).
func setupTestDB(t *testing.T) (*gorm.DB, func()) {
	t.Helper()
	db, err := gorm.Open(sqlite.Open(":memory:"))
	if err != nil {
		t.Fatalf("open sqlite: %v", err)
	}
	if err := db.AutoMigrate(&model.ApiKey{}); err != nil {
		t.Fatalf("auto migrate: %v", err)
	}
	return db, func() { _ = db }
}

// mustInsertKey is a test helper that inserts an ApiKey row and fails
// the test on error. The id field is generated by the caller; the rest
// of the struct is supplied as arguments.
func mustInsertKey(t *testing.T, db *gorm.DB, id, key string, active *bool) {
	t.Helper()
	k := model.ApiKey{ID: id, Key: key, IsActive: active}
	if err := db.Create(&k).Error; err != nil {
		t.Fatalf("insert api key %q: %v", key, err)
	}
}

// TestAPIKeyValidator_ValidKey exercises AC-001: a key that exists and
// is active passes when requireApiKey is true.
func TestAPIKeyValidator_ValidKey(t *testing.T) {
	db, teardown := setupTestDB(t)
	defer teardown()
	mustInsertKey(t, db, "1", "sk-valid", boolPtr(true))

	v := newAPIKeyValidator(db)
	if err := v.Validate(true, "sk-valid"); err != nil {
		t.Errorf("valid key rejected: %v", err)
	}
}

// TestAPIKeyValidator_MissingKey exercises AC-002: empty key with
// requireApiKey=true is rejected as "Missing API key".
func TestAPIKeyValidator_MissingKey(t *testing.T) {
	db, teardown := setupTestDB(t)
	defer teardown()

	v := newAPIKeyValidator(db)
	err := v.Validate(true, "")
	if err == nil {
		t.Fatal("expected error for missing key, got nil")
	}
	if !errors.Is(err, errAPIKeyRejected) {
		t.Errorf("error = %v, want errAPIKeyRejected", err)
	}
	if err.Error() != "api key rejected: Missing API key" {
		t.Errorf("message = %q, want %q", err.Error(), "api key rejected: Missing API key")
	}
}

// TestAPIKeyValidator_InvalidKey exercises AC-003: a key that does not
// exist in the table is rejected as "Invalid API key".
func TestAPIKeyValidator_InvalidKey(t *testing.T) {
	db, teardown := setupTestDB(t)
	defer teardown()

	v := newAPIKeyValidator(db)
	err := v.Validate(true, "sk-invalid")
	if err == nil {
		t.Fatal("expected error for unknown key, got nil")
	}
	if !errors.Is(err, errAPIKeyRejected) {
		t.Errorf("error = %v, want errAPIKeyRejected", err)
	}
	if err.Error() != "api key rejected: Invalid API key" {
		t.Errorf("message = %q, want %q", err.Error(), "api key rejected: Invalid API key")
	}
}

// TestAPIKeyValidator_Disabled exercises AC-005: a key that exists but
// has isActive=false is rejected as "Invalid API key" (not "Missing
// API key").
func TestAPIKeyValidator_Disabled(t *testing.T) {
	db, teardown := setupTestDB(t)
	defer teardown()
	mustInsertKey(t, db, "1", "sk-disabled", boolPtr(false))

	v := newAPIKeyValidator(db)
	err := v.Validate(true, "sk-disabled")
	if err == nil {
		t.Fatal("expected error for disabled key, got nil")
	}
	if !errors.Is(err, errAPIKeyRejected) {
		t.Errorf("error = %v, want errAPIKeyRejected", err)
	}
	if err.Error() != "api key rejected: Invalid API key" {
		t.Errorf("message = %q, want %q", err.Error(), "api key rejected: Invalid API key")
	}
}

// TestAPIKeyValidator_RequireFalse exercises AC-004: when
// requireApiKey=false, ANY key (including empty) is accepted without
// touching the database.
func TestAPIKeyValidator_RequireFalse(t *testing.T) {
	db, teardown := setupTestDB(t)
	defer teardown()

	v := newAPIKeyValidator(db)
	if err := v.Validate(false, ""); err != nil {
		t.Errorf("requireApiKey=false should bypass check, got: %v", err)
	}
	if err := v.Validate(false, "sk-anything"); err != nil {
		t.Errorf("requireApiKey=false should bypass check, got: %v", err)
	}
}

// TestAPIKeyValidator_NilIsActive exercises AC-005 variant: a key
// whose isActive column is NULL (the *bool nil case) is treated as
// inactive and rejected.
func TestAPIKeyValidator_NilIsActive(t *testing.T) {
	db, teardown := setupTestDB(t)
	defer teardown()
	// Insert without setting IsActive — GORM stores the zero value.
	mustInsertKey(t, db, "1", "sk-nilactive", nil)

	v := newAPIKeyValidator(db)
	err := v.Validate(true, "sk-nilactive")
	if err == nil {
		t.Fatal("expected error for nil-IsActive key, got nil")
	}
	if !errors.Is(err, errAPIKeyRejected) {
		t.Errorf("error = %v, want errAPIKeyRejected", err)
	}
}

// TestValidateAPIKey_HandlerIntegration exercises the full HTTP handler
// path: when the validator rejects, ChatCompletionsHandler must return
// 401 with the OpenAI error envelope.
func TestValidateAPIKey_HandlerIntegration(t *testing.T) {
	db, teardown := setupTestDB(t)
	defer teardown()

	v := newAPIKeyValidator(db)
	err := v.Validate(true, "sk-invalid")
	if err == nil {
		t.Fatal("expected validation error")
	}

	// Verify the error message matches what WriteError would emit.
	expectedMsg := "Invalid API key"
	if err.Error() != "api key rejected: Invalid API key" {
		t.Errorf("error message mismatch: got %q, want ending %q", err.Error(), expectedMsg)
	}

	// WriteError should produce 401 with the OpenAI envelope.
	w := httptest.NewRecorder()
	WriteError(w, http.StatusUnauthorized, expectedMsg)
	resp := w.Result()
	if resp.StatusCode != http.StatusUnauthorized {
		t.Errorf("status = %d, want %d", resp.StatusCode, http.StatusUnauthorized)
	}
}

// boolPtr is a small test helper that returns a *bool pointing to the
// supplied value. It is intentionally local to this file to avoid
// polluting the package API.
func boolPtr(v bool) *bool {
	return &v
}
